name: Emacs Lisp CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version:
          - "snapshot"
          - "30.1"
          - "29.4"
          - "28.2"
        include:
          - os: ubuntu-latest
            emacs_version: "27.2"

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
      # To create test report checks
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Set up Eask
        uses: emacs-eask/setup-eask@master
        with:
          version: "snapshot"

      - name: Run tests
        env:
          EMACS_TEST_JUNIT_REPORT: ${{ (matrix.emacs_version != '27.2' && matrix.emacs_version != '28.2') && 'mcp-server-lib-test.xml' || '' }}
        run: |
          eask clean all
          eask package
          eask install
          eask compile
          eask lint elisp-lint
          eask lint keywords
          eask lint regexps
          eask run script test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: matrix.emacs_version != '27.2' && matrix.emacs_version != '28.2'
        with:
          name: test-results-${{ matrix.os }}-emacs-${{ matrix.emacs_version }}
          path: mcp-server-lib-test.xml
          retention-days: 7

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: matrix.emacs_version != '27.2' && matrix.emacs_version != '28.2'
        with:
          name: Test Results - ${{ matrix.os }} - Emacs ${{ matrix.emacs_version }}
          path: mcp-server-lib-test.xml
          reporter: java-junit
