name: MCP stdio Adapter Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  stdio-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version:
          - "snapshot"
          - "30.1"
          - "29.4"
          - "28.2"

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Emacs
        uses: purcell/setup-emacs@master # zizmor: ignore[unpinned-uses]
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run stdio adapter tests
        run: ./emacs-mcp-stdio-test.sh
