name: MCP StdIO Adapter Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  stdio-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - "snapshot"
          - "30.1"
          - "29.4"
          - "28.2"

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run StdIO adapter tests
        run: ./emacs-mcp-stdio-test.sh
